// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAyaP-VbAImIHg5pfFpn2C9OsTGRZhHg0',
    appId: '1:52139565225:web:3e28765c22aac9aa3489b8',
    messagingSenderId: '52139565225',
    projectId: 'colorex-37fd5',
    authDomain: 'colorex-37fd5.firebaseapp.com',
    storageBucket: 'colorex-37fd5.appspot.com',
    measurementId: 'G-456FY5LJ4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTevNGZbPGYM2JN-cRV6y194oNI9du-4',
    appId: '1:52139565225:android:28fb37d2e38f20873489b8',
    messagingSenderId: '52139565225',
    projectId: 'colorex-37fd5',
    storageBucket: 'colorex-37fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWs9Atoe-71A25kMIyrZsOmHvR9l_uuUA',
    appId: '1:52139565225:ios:89763306f712d0453489b8',
    messagingSenderId: '52139565225',
    projectId: 'colorex-37fd5',
    storageBucket: 'colorex-37fd5.appspot.com',
    androidClientId: '52139565225-otiv7kos5ie85c4nfth8olta6kr7lbm4.apps.googleusercontent.com',
    iosClientId: '52139565225-lketego5r5os9domvjnvjjef1gpan579.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWs9Atoe-71A25kMIyrZsOmHvR9l_uuUA',
    appId: '1:52139565225:ios:89763306f712d0453489b8',
    messagingSenderId: '52139565225',
    projectId: 'colorex-37fd5',
    storageBucket: 'colorex-37fd5.appspot.com',
    androidClientId: '52139565225-otiv7kos5ie85c4nfth8olta6kr7lbm4.apps.googleusercontent.com',
    iosClientId: '52139565225-lketego5r5os9domvjnvjjef1gpan579.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAyaP-VbAImIHg5pfFpn2C9OsTGRZhHg0',
    appId: '1:52139565225:web:985816332047032d3489b8',
    messagingSenderId: '52139565225',
    projectId: 'colorex-37fd5',
    authDomain: 'colorex-37fd5.firebaseapp.com',
    storageBucket: 'colorex-37fd5.appspot.com',
    measurementId: 'G-112PBE3C42',
  );

}